### ISSUE TITLE
Operator install fails to run on GKE because of missing command

### ISSUE THREAD

**Issue by Dynatrace-BrianWilson** [keptn-workshops/workshop-instructions#2]
First kubectl command for the GKE operator install should be `kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=$(gcloud config get-value account)`
as documented [here](https://www.dynatrace.com/support/help/technology-support/cloud-platforms/google-cloud-platform/google-kubernetes-engine/installation-and-operation/full-stack/deploy-oneagent-on-google-kubernetes-engine-clusters/) 

Deployment of OneAgent Operator fails without it.  Yes - I'm using my Dynatrace GCP account. However, that step is documented as step one for GKE regardless.

**Comment by Dynatrace-BrianWilson** [comment]
perhaps that can be added to the deployDynatraceOnGKE.sh script before invoking the common script

**Comment by jetzlstorfer** [comment]
Hi @Dynatrace-BrianWilson ,
indeed that step is necessary, thanks for mentioning it. I'll add it in the instructions.

**Comment by jetzlstorfer** [comment]
It's now added to the instructions: https://github.com/keptn-workshops/workshop-instructions/blob/master/README.md#3-install-dynatrace
