### ISSUE TITLE
Suggestion for the workshop- ketpn auth

### ISSUE THREAD

**Issue by Dynatrace-BrianWilson** [keptn-workshops/workshop-instructions#4]
I'm not sure if this applies similarly to AWS and Azure, but it applies to GCP for sure. 
I'm doing the workshop in my spare time over a couple of days.  Everytime I exit out of the workshop container, the container gets destroyed.  When I continue, I have to start a new instance of the container.  
In the instructions, you already describe how "Setup the Kubernetes cluster or connection to the cluster."

What's missing is that keptn resources cannot be added because there is no keptn auth configured in the new container. 

I found instructions on the kepth.sh cli page, however, for the workshop it might be useful to either include instruction to re-authorize or a simple script to re-authorize (I prefer instructions so users get familiar with the commands) if the message 'Error: This command requires to be authenticated. See "keptn auth" for details'

**Comment by jetzlstorfer** [comment]
Hi @Dynatrace-BrianWilson ,
correct, when following the instructions from this repo the container will be gone once disconnected. However, there is a script inside the container `scripts/authme.sh` which you can run to authenticate the Keptn CLI again to the cluster.

**Comment by jetzlstorfer** [comment]
There is another option of running the docker container in the background so it won't be killed when exiting. I'll add instructions for this option as well.

**Comment by jetzlstorfer** [comment]
Updated instructions how to start the container so it won't be killed after you exit.
